apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agennext-chat.fullname" . }}
  labels:
    {{- include "agennext-chat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "agennext-chat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agennext-chat.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "agennext-chat.serviceAccountName" . }}
      containers:
        - name: agennextd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
