{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agennext-chat.serviceAccountName" . }}
  labels:
    {{- include "agennext-chat.labels" . | nindent 4 }}
{{- end -}}
